dbf2tab.c: Add missing function types, fix compiler warnings
This happened with gcc 5.4.0 on Linux Mint 18:

  cc -Werror -o dbf2tab dbf2tab.c
  dbf2tab.c:113:1: error: return type defaults to ‘int’ [-Werror=implicit-int]
   fatal_err( msg)
   ^
  dbf2tab.c:122:1: error: return type defaults to ‘int’ [-Werror=implicit-int]
   get_header()
   ^
  dbf2tab.c:189:1: error: return type defaults to ‘int’ [-Werror=implicit-int]
   get_rec()
   ^
  dbf2tab.c:230:1: error: return type defaults to ‘int’ [-Werror=implicit-int]
   usage()
   ^
  dbf2tab.c:241:1: error: return type defaults to ‘int’ [-Werror=implicit-int]
   main(argc, argv)
   ^
  cc1: all warnings being treated as errors
  Makefile:5: recipe for target 'dbf2tab' failed
  make[2]: *** [dbf2tab] Error 1

7506fe78-a547-11e7-8a2f-f74d993421b0