Upgrade youtube-dl to version 2018.11.07
Fixes this problem:

  $ yd https://www.youtube.com/watch?v=aBQIAWh3YBs -F
  [youtube] aBQIAWh3YBs: Downloading webpage
  [youtube] aBQIAWh3YBs: Downloading video info webpage
  [youtube] aBQIAWh3YBs: Downloading js player vfl6LN1Nj
  ERROR: Signature extraction failed: Traceback (most recent call last):
    File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py",
    line 1221, in _decrypt_signature
      video_id, player_url, s
    File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py",
    line 1130, in _extract_signature_function
      res = self._parse_sig_js(code)
    File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py",
    line 1193, in _parse_sig_js
      jscode, 'Initial JS player signature function name', group='sig')
    File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/common.py",
    line 977, in _search_regex
      raise RegexNotFoundError('Unable to extract %s' % _name)
  RegexNotFoundError: Unable to extract Initial JS player signature
  function name; please report this issue on https://yt-dl.org/bug .
  Make sure you are using the latest version; type  youtube-dl -U  to
  update. Be sure to call youtube-dl with the --verbose flag and include
  its complete output.
   (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial
  JS player signature function name\x1b[0m; please report this issue on
  https://yt-dl.org/bug . Make sure you are using the latest version;
  type  youtube-dl -U  to update. Be sure to call youtube-dl with the
  --verbose flag and include its complete output.',)); please report
  this issue on https://yt-dl.org/bug . Make sure you are using the
  latest version; type  youtube-dl -U  to update. Be sure to call
  youtube-dl with the --verbose flag and include its complete output.
  $

d4810094-e54f-11e8-baf9-db5caa6d21d3