Upgrade youtube-dl to version 2020.01.24
Fixes this problem:

```
$ yd 52-RAKDAQO0 -F
[youtube] 52-RAKDAQO0: Downloading webpage
[youtube] 52-RAKDAQO0: Downloading video info webpage
[youtube] 52-RAKDAQO0: Downloading js player vfl_PLd61
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1384, in _decrypt_signature
    video_id, player_url, s
  File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1297, in _extract_signature_function
    cache_res = res(test_string)
  File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1360, in <lambda>
    return lambda s: initial_function([s])
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please
report this issue on https://yt-dl.org/bug . Make sure you are using the
latest version; type  youtube-dl -U  to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Unsupported JS expression
u'[function(c,d){d=(d'; please report this issue on
https://yt-dl.org/bug . Make sure you are using the latest version; type
youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.",)); please report this issue on
https://yt-dl.org/bug . Make sure you are using the latest version; type
youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
```

6d1cf4ca-3e41-11ea-9db9-db5caa6d21d3