Make CI/CD work on gitlab.com, squash 2 commits
I have an unbroken green CI/CD streak on gitlab.com since commit
`375e0919cadb` ("Create .gitlab-ci.yml, `make` and `make test` work in
Gitlab CI", 2019-06-01, 6.19 years ago), there's no way some random
updates on gitlab.com shall break it. Even if it means to commit 2
unrelated changes together:

- tests/Makefile: Disable datefn.t temporarily on gitlab.com
- sident.t: Send stderr to stdout to work with old and new versions of
  podchecker(1).

Squashed commit of the following:

```
commit 40532bfab22e8bf4bd87e91961e070d94f0aea6d
Author: Øyvind A. Holm <sunny@sunbase.org>
Date:   Wed Aug 13 20:10:56 2025 +0200

    WTF, sident.t also fails on Gitlab. See if this works.

    Commit ID: ea1348b6-7870-11f0-8095-83850402c3ce

commit 64bdf395c04cbfbda2365fc516d3a17e98af0407
Author: Øyvind A. Holm <sunny@sunbase.org>
Date:   Wed Aug 13 19:13:54 2025 +0200

    tests/Makefile: Disable datefn.t on Gitlab, the locale there is wacked up

    This happened in <https://gitlab.com/oyvholm/utils/-/jobs/11009565568>:

    ```tap
    # Test -l/--local option
    ok 82 - chdir datefn-files
    ok 83 - mkdir datefn-tmp
    ok 84 - Copy small.dsd_5330.jpg to datefn-tmp/dsd_5330.jpg
    # Test -l option
    # Use timezone CET
    not ok 85 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=CET, -l) (stdout)
    #   Failed test 'Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=CET, -l) (stdout)'
    #   at ./datefn.t line 602.
    #          got: 'datefn: 'datefn-tmp/dsd_5330.jpg' renamed to 'datefn-tmp/20090706T213604Z.dsd_5330.jpg'
    # '
    #     expected: 'datefn: 'datefn-tmp/dsd_5330.jpg' renamed to 'datefn-tmp/20090706T193604Z.dsd_5330.jpg'
    # '
    ok 86 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=CET, -l) (stderr)
    ok 87 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=CET, -l) (retval)
    not ok 88 - datefn-tmp/20090706T193604Z.dsd_5330.jpg exists
    #   Failed test 'datefn-tmp/20090706T193604Z.dsd_5330.jpg exists'
    #   at ./datefn.t line 499.
    not ok 89 - Remove timestamp from dsd_5330.jpg after -l
    #   Failed test 'Remove timestamp from dsd_5330.jpg after -l'
    #   at ./datefn.t line 501.
    # Use timezone EST
    not ok 90 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=EST, -l) (stdout)
    #   Failed test 'Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=EST, -l) (stdout)'
    #   at ./datefn.t line 602.
    #          got: ''
    #     expected: 'datefn: 'datefn-tmp/dsd_5330.jpg' renamed to 'datefn-tmp/20090707T023604Z.dsd_5330.jpg'
    # '
    not ok 91 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=EST, -l) (stderr)
    #   Failed test 'Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=EST, -l) (stderr)'
    #   at ./datefn.t line 605.
    #          got: 'datefn: datefn-tmp/dsd_5330.jpg: Not a regular file
    # '
    #     expected: ''
    ok 92 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=EST, -l) (retval)
    not ok 93 - datefn-tmp/20090707T023604Z.dsd_5330.jpg exists
    #   Failed test 'datefn-tmp/20090707T023604Z.dsd_5330.jpg exists'
    #   at ./datefn.t line 499.
    not ok 94 - Remove timestamp from dsd_5330.jpg after -l
    #   Failed test 'Remove timestamp from dsd_5330.jpg after -l'
    #   at ./datefn.t line 501.
    # Use timezone UTC
    not ok 95 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=UTC, -l) (stdout)
    #   Failed test 'Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=UTC, -l) (stdout)'
    #   at ./datefn.t line 602.
    #          got: ''
    #     expected: 'datefn: 'datefn-tmp/dsd_5330.jpg' renamed to 'datefn-tmp/20090706T213604Z.dsd_5330.jpg'
    # '
    [Cut 188 lines]
    1..237
    # Looks like you failed 41 tests of 237.
    make[1]: *** [Makefile:34: test] Error 41
    make[1]: Leaving directory '/builds/oyvholm/utils/tests'
    make: *** [Makefile:73: test] Error 2
    section_end:1755101732:step_script
    section_start:1755101732:cleanup_file_variables
    Cleaning up project directory and file based variables
    section_end:1755101733:cleanup_file_variables
    ERROR: Job failed: exit code 1
    ```

    Almost all the tests that use the -l/--local option fail:

    ```tap
    not ok 85 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=CET, -l) (stdout)
    not ok 88 - datefn-tmp/20090706T193604Z.dsd_5330.jpg exists
    not ok 89 - Remove timestamp from dsd_5330.jpg after -l
    not ok 90 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=EST, -l) (stdout)
    not ok 91 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=EST, -l) (stderr)
    not ok 93 - datefn-tmp/20090707T023604Z.dsd_5330.jpg exists
    not ok 94 - Remove timestamp from dsd_5330.jpg after -l
    not ok 95 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=UTC, -l) (stdout)
    not ok 96 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=UTC, -l) (stderr)
    not ok 100 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=CET, --local) (stdout)
    not ok 103 - datefn-tmp/20090706T193604Z.dsd_5330.jpg exists
    not ok 104 - Remove timestamp from dsd_5330.jpg after --local
    not ok 105 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=EST, --local) (stdout)
    not ok 106 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=EST, --local) (stderr)
    not ok 108 - datefn-tmp/20090707T023604Z.dsd_5330.jpg exists
    not ok 109 - Remove timestamp from dsd_5330.jpg after --local
    not ok 110 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=UTC, --local) (stdout)
    not ok 111 - Use EXIF data from datefn-tmp/dsd_5330.jpg (TZ=UTC, --local) (stderr)
    not ok 120 - Use mtime from file.txt with -l, tz = CET (stdout)
    not ok 123 - 20121223T232858Z.file.txt exists after -l and tz = CET
    not ok 124 - Rename 20121223T232858Z.file.txt back to file.txt
    not ok 125 - Use mtime from file.txt with -l, tz = EST (stdout)
    not ok 126 - Use mtime from file.txt with -l, tz = EST (stderr)
    not ok 128 - 20121224T052858Z.file.txt exists after -l and tz = EST
    not ok 129 - Rename 20121224T052858Z.file.txt back to file.txt
    not ok 130 - Use mtime from file.txt with -l, tz = UTC (stdout)
    not ok 131 - Use mtime from file.txt with -l, tz = UTC (stderr)
    not ok 133 - 20121224T002858Z.file.txt exists after -l and tz = UTC
    not ok 134 - Rename 20121224T002858Z.file.txt back to file.txt
    not ok 135 - Use mtime from file.txt with --local, tz = CET (stdout)
    not ok 136 - Use mtime from file.txt with --local, tz = CET (stderr)
    not ok 138 - 20121223T232858Z.file.txt exists after --local and tz = CET
    not ok 139 - Rename 20121223T232858Z.file.txt back to file.txt
    not ok 140 - Use mtime from file.txt with --local, tz = EST (stdout)
    not ok 141 - Use mtime from file.txt with --local, tz = EST (stderr)
    not ok 143 - 20121224T052858Z.file.txt exists after --local and tz = EST
    not ok 144 - Rename 20121224T052858Z.file.txt back to file.txt
    not ok 145 - Use mtime from file.txt with --local, tz = UTC (stdout)
    not ok 146 - Use mtime from file.txt with --local, tz = UTC (stderr)
    not ok 148 - 20121224T002858Z.file.txt exists after --local and tz = UTC
    not ok 149 - Rename 20121224T002858Z.file.txt back to file.txt
    ```

    even though the changes I'd made in Lib/std/c/ are totally unrelated.
    Not much to do about it, so just disable it on Gitlab for now.

    Commit ID: f266c2d2-786a-11f0-be9d-83850402c3ce
```

Commit ID: f138f178-7874-11f0-867c-83850402c3ce