Upgrade youtube-dl to version 2018.09.08
Seems to fix a problem with some videos that won't download:

  $ ydf https://www.youtube.com/watch?v=BMcA2YPpbOk
  [youtube] BMcA2YPpbOk: Downloading webpage
  [youtube] BMcA2YPpbOk: Downloading video info webpage
  [youtube] BMcA2YPpbOk: Downloading js player vflIVQ4xT
  ERROR: Signature extraction failed: Traceback (most recent call last):
    File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py",
    line 1210, in _decrypt_signature
      video_id, player_url, s
    File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py",
    line 1121, in _extract_signature_function
      res = self._parse_sig_js(code)
    File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py",
    line 1182, in _parse_sig_js
      jscode, 'Initial JS player signature function name', group='sig')
    File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/common.py",
    line 972, in _search_regex
      raise RegexNotFoundError('Unable to extract %s' % _name)
  RegexNotFoundError: Unable to extract Initial JS player signature
  function name; please report this issue on https://yt-dl.org/bug .
  Make sure you are using the latest version; type  youtube-dl -U  to
  update. Be sure to call youtube-dl with the --verbose flag and include
  its complete output.
   (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial
  JS player signature function name\x1b[0m; please report this issue on
  https://yt-dl.org/bug . Make sure you are using the latest version;
  type  youtube-dl -U  to update. Be sure to call youtube-dl with the
  --verbose flag and include its complete output.',)); please report
  this issue on https://yt-dl.org/bug . Make sure you are using the
  latest version; type  youtube-dl -U  to update. Be sure to call
  youtube-dl with the --verbose flag and include its complete output.

ad47cf96-b37a-11e8-a8dd-db5caa6d21d3