Upgrade youtube-dl to version 2020.07.28
Fixes this problem:

```
$ yd -F https://www.youtube.com/watch?v=Snq7SBJ3YZM
[youtube] Snq7SBJ3YZM: Downloading webpage
[youtube] Snq7SBJ3YZM: Downloading js player f82a8c37
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1426, in _decrypt_signature
    video_id, player_url, s
  File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1338, in _extract_signature_function
    cache_res = res(test_string)
  File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1402, in <lambda>
    return lambda s: initial_function([s])
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 92, in interpret_expression
    m.group('expr'), local_vars, allow_recursion - 1)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 189, in interpret_expression
    m.group('x'), local_vars, allow_recursion - 1)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'['; please report this issue
on https://yt-dl.org/bug . Make sure you are using the latest version;
type  youtube-dl -U  to update. Be sure to call youtube-dl with the
--verbose flag and include its complete output.
 (caused by ExtractorError(u"Unsupported JS expression u'['; please
report this issue on https://yt-dl.org/bug . Make sure you are using the
latest version; type  youtube-dl -U  to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.",));
please report this issue on https://yt-dl.org/bug . Make sure you are
using the latest version; type  youtube-dl -U  to update. Be sure to
call youtube-dl with the --verbose flag and include its complete output.
```

`youtube-dl -U` hasn't worked for a couple of months, downloaded from
<https://github.com/ytdl-org/youtube-dl/releases>.

c67c7bf4-d1ac-11ea-926d-db5caa6d21d3