list-youtube: Add missing `""` around one `$db`
It didn't work in directories with whitespace in the path name:

    $ list-youtube
    /home/sunny/bin/list-youtube: line 131: test: too many arguments
    Error: near line 2: no such table: yt
    $

Quote `$db` properly in the offending line.

49621e9a-920f-11e9-9e27-4f45262dc9b5