Upgrade yt-dlp to version 2022.04.08
```
$ yt-dlp -U
Latest version: 2022.04.08, Current version: 2022.01.21
Current Build Hash b0ad39841b1de2e608336d430958102fed4f2cbe5976690aed71b0c81d949fca
Updating to version 2022.04.08 ...
Updated yt-dlp to version 2022.04.08; Restart yt-dlp to use the new version
```

Fixes this problem:

```
$ yd -f 401+251 https://www.youtube.com/watch?v=NL0TNGfcge4
[youtube] NL0TNGfcge4: Downloading webpage
[youtube] NL0TNGfcge4: Downloading android player API JSON
[youtube] NL0TNGfcge4: Downloading player 534c466c
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = m4ZWaJ6Qmq1W26dFi ; player = https://www.youtube.com/s/player/534c466c/player_ias.vflset/en_US/base.js
NL0TNGfcge4: Traceback (most recent call last):
  File "/home/sunny/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2412, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/home/sunny/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2433, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/home/sunny/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2423, in _extract_n_function_name
    jscode, 'Initial JS player n function name', group='nfunc')
  File "/home/sunny/bin/yt-dlp/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n
function name; please report this issue on
https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest
version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the
--verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS
 player n function name\x1b[0m; please report this issue on
 https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest
 version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the
 --verbose flag and include its complete output.')); please report this
 issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using
 the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp
 with the --verbose flag and include its complete output.
```

4052bc34-c46f-11ec-aa1c-5582e081d110