Sync git-remote-hg with new source, github.com/fingolfin/git-remote-hg
git-remote-hg stopped working after I upgraded Mercurial to 3.6.3:

  2016-01-12 09:20:59 sunny@linode:~/src/hggit/mutt (home-sunny *)
  $ PYTHONPATH=/usr/local/lib/python2.7/site-packages git clone hg::http://dev.mutt.org/hg/mutt
  Cloning into 'mutt'...
  Traceback (most recent call last):
    File "/home/sunny/bin/git-remote-hg", line 1322, in <module>
      sys.exit(main(sys.argv))
    File "/home/sunny/bin/git-remote-hg", line 1286, in main
      repo = get_repo(url, alias)
    File "/home/sunny/bin/git-remote-hg", line 433, in get_repo
      repo.pull(peer, heads=None, force=True)
    File "/usr/local/lib/python2.7/site-packages/mercurial/repoview.py", line 339, in __getattr__
      return getattr(self._unfilteredrepo, attr)
  AttributeError: 'localrepository' object has no attribute 'pull'
  2016-01-12 09:21:02 sunny@linode:~/src/hggit/mutt (home-sunny *)
  $

According to <https://github.com/felipec/git-remote-hg/issues/27> it's
broken by Mercurial 3.2 . github.com/felipec/git-remote-hg.git hasn't
been updated since 2014-06-03, but this fork at
<git@github.com:fingolfin/git-remote-hg.git> fixes this problem and
seems to work great out of the box. Synced against the newest commit
bd8c46e1ea29d192bb8ad67708b33ea59d396b7a from 2015-12-07.

Also update synced.sql with the new location and timestamp when it was
updated.

a22c32c2-b90a-11e5-9ca0-fefdb24f8e10