youtube-dl: Updated to v2013.11.28.1 using an older version
Had to reset HEAD to aeefa98 (version 2013.11.15.1) to be able to use
"youtube-dl -U". When using version 2013.11.22.2 at 5ca09ba, this
happened:

  2013-11-28 17:09:48 sunny@ubstud:~/bin (master % u=)
  $ youtube-dl -U
  Traceback (most recent call last):
    File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
      "__main__", fname, loader, pkg_name)
    File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
      exec code in run_globals
    File "/home/sunny/bin/youtube-dl/__main__.py", line 18, in <module>
    File "/home/sunny/bin/youtube-dl/youtube_dl/__init__.py", line 774, in main
    File "/home/sunny/bin/youtube-dl/youtube_dl/__init__.py", line 717, in _real_main
    File "/home/sunny/bin/youtube-dl/youtube_dl/update.py", line 89, in update_self
  NameError: global name 'version_str' is not defined

  2013-11-28 17:10:05 sunny@ubstud:~/bin (master % u=)
  $ git co aeefa98
  HEAD is now at aeefa98... youtube-dl: Updated to version 2013.11.15.1

  2013-11-28 17:10:07 sunny@ubstud:~/bin ((aeefa98...) %)
  $ youtube-dl -U
  Updating to version 2013.11.28.1...
  Updated youtube-dl. Restart youtube-dl to use the new version.

0b9e2bcc-5849-11e3-9551-001f3b596ec9