Upgrade youtube-dl to version 2019.06.21
Fixes this problem:

    $ ydf ZUWpHU_V1II
    [youtube] ZUWpHU_V1II: Downloading webpage
    [youtube] ZUWpHU_V1II: Downloading video info webpage
    [youtube] ZUWpHU_V1II: Downloading js player vfl49f_g4
    ERROR: Signature extraction failed: Traceback (most recent call last):
      File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py",
      line 1342, in _decrypt_signature
        video_id, player_url, s
      File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py",
      line 1250, in _extract_signature_function
        res = self._parse_sig_js(code)
      File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py",
      line 1314, in _parse_sig_js
        jscode, 'Initial JS player signature function name', group='sig')
      File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/common.py",
      line 1005, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract Initial JS player signature
    function name; please report this issue on https://yt-dl.org/bug .
    Make sure you are using the latest version; type  youtube-dl -U  to
    update. Be sure to call youtube-dl with the --verbose flag and
    include its complete output.
     (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial
    JS player signature function name\x1b[0m; please report this issue
    on https://yt-dl.org/bug . Make sure you are using the latest
    version; type  youtube-dl -U  to update. Be sure to call youtube-dl
    with the --verbose flag and include its complete output.',)); please
    report this issue on https://yt-dl.org/bug . Make sure you are using
    the latest version; type  youtube-dl -U  to update. Be sure to call
    youtube-dl with the --verbose flag and include its complete output.

7dd7df7e-9490-11e9-800c-db5caa6d21d3