Upgrade youtube-dl to version 2019.01.17
Fixes this problem:

  $ ydf https://www.youtube.com/watch?v=TquzJd90lAE
  [youtube] TquzJd90lAE: Downloading webpage
  [youtube] TquzJd90lAE: Downloading video info webpage
  [youtube] TquzJd90lAE: Downloading js player vfl-jbnrr
  ERROR: Signature extraction failed: Traceback (most recent call last):
    File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1226, in _decrypt_signature
      video_id, player_url, s
    File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1134, in _extract_signature_function
      res = self._parse_sig_js(code)
    File "/home/sunny/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1201, in _parse_sig_js
      initial_function = jsi.extract_function(funcname)
    File "/home/sunny/bin/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
      raise ExtractorError('Could not find JS function %r' % funcname)
  ExtractorError: Could not find JS function u'encodeURIComponent';
  please report this issue on https://yt-dl.org/bug . Make sure you are
  using the latest version; type  youtube-dl -U  to update. Be sure to
  call youtube-dl with the --verbose flag and include its complete
  output.
   (caused by ExtractorError(u"Could not find JS function
   u'encodeURIComponent'; please report this issue on
   https://yt-dl.org/bug . Make sure you are using the latest version;
   type  youtube-dl -U  to update. Be sure to call youtube-dl with the
   --verbose flag and include its complete output.",)); please report
   this issue on https://yt-dl.org/bug . Make sure you are using the
   latest version; type  youtube-dl -U  to update. Be sure to call
   youtube-dl with the --verbose flag and include its complete output.

2a018d34-1b17-11e9-822a-db5caa6d21d3